# Generated by Django 5.0 on 2023-12-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Species' name", max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the species')),
                ('diet', models.CharField(choices=[('endangered', 'Endangered'), ('vulnerable', 'Vulnerable'), ('least concern', 'Least Concern')], help_text='UICN conservation status for the species')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the zone', max_length=100)),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('temperate', 'Temperate'), ('arctic', 'Arctic')], help_text='Climate type of the zone')),
                ('area', models.IntegerField(help_text='The area of the zone in square meters')),
            ],
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Keeper's name", max_length=100)),
                ('hire_date', models.DateField(auto_now_add=True, help_text='Date the keeper was hired')),
                ('zones', models.ManyToManyField(help_text='Zones in which the keeper works', related_name='keepers', to='zoo.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Animal's name", max_length=100)),
                ('birth_date', models.DateField(help_text="Animal's birthdate")),
                ('diet', models.CharField(choices=[('carnivore', 'Carnivore'), ('omnivore', 'Omnivore'), ('herbivore', 'Herbivore')], help_text="Animal's diet category")),
                ('weight', models.FloatField(help_text="Animal's weight in kilos")),
                ('species', models.ForeignKey(help_text="Animal's species", on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.species')),
                ('zone', models.ForeignKey(help_text='Zone where the animal is kept', on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='zoo.zone')),
            ],
        ),
    ]
