# Generated by Django 5.0 on 2023-12-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
