# Generated by Django 5.0 on 2023-12-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_rename_birth_date_animal_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='diet',
            new_name='conservation',
        ),
    ]
